### ISSUE TITLE
[frontend] 지역&루트 선택 컴포넌트 개편

### ISSUE THREAD

**Issue by tech-hoon** [TravelPlan-Project/TravelPlan#121]
- [x] 지역 선택 페이지 -> 메인 화면에서, 지역 및 루트 선택하는 컴포넌트로 변경 (selectContainer)
- [x] selectContainer : 지역 선택(selectArea) + 루트 선택(selectRoute)로 구성
- [x] 경로 선택 후 주소 변경 : "/(지역명)/routes" -> "/routes"
- [ ] 지역 선택 후 주소 : "/(지역명)/places" -> "/places"     // 지역 별 좌표 값 아직 안 정해서
- [ ] 루트 선택하면, 그 루트로 바로 보여주기

**Comment by taekhun** [comment]
- 지역선택페이지 -> 메인 화면에서, 지역 선택하는 컴포넌트로 변경 (selectContainer)
- 지역 선택(selectArea) + 루트 선택(selectRoute)로 구성
