### ISSUE TITLE
[backend] 도메인 확정 및 서버 구축

### ISSUE THREAD

**Issue by labyu** [TravelPlan-Project/TravelPlan#18]
@taekhun  @Kwongiseok 

서비스 이름이 확정되어서 도메인 구입후 상시 동작할 서버를 띄우기 위해 문의드립니다.

도메인명은 어떻게 하면 좋을까요? ~~~.me 이나 ~~~.com으루 ㅎㅎ. 

저는 baruntravel.me 생각해보았습니다

**Comment by Kwongiseok** [comment]
baruntavel.me 좋은 것 같아요!

**Comment by labyu** [comment]
오타가 있었군요 ㅎㅎ.. `baruntravel.me` 구매 완료했습니다

**Comment by labyu** [comment]
mysql.labyu.me:3306 프로젝트용 데이터베이스 생성 및 계정 생성

username : baruntravel
password : 카카오톡 공유

```
CREATE USER 'baruntravel'@'%' IDENTIFIED BY '';
GRANT ALL ON `baruntravel`.* TO 'baruntravel'@'%';
FLUSH PRIVILEGES;
```

**Comment by labyu** [comment]
서버 구축 및 Develop Branch CI/CD 작업이 끝났습니다.

앞으로 develop branch push event (pr에서 develop브랜치로 머지하는 것도 이 이벤트임) 가 발생하면 자동으로 서버가 업데이트 됩니다.

백엔드 개발 진행될때마다 API문서 업데이트 에정입니다.

프론트 서버 : baruntravel.me
백엔드 서버 : api.baruntravel.me
백엔드 API 문서 : api.baruntravel.me/docs/index.html
