### ISSUE TITLE
[backend] 경로 DB 및 경로 생성 API에 지역(area) 추가 요청

### ISSUE THREAD

**Issue by tech-hoon** [TravelPlan-Project/TravelPlan#63]
@Kwongiseok @labyu

1. 한 지역의 루트들을 보여주는`/{area id}/routes` 페이지에서
지역(`area`, ex:이태원)에 맞는 루트를 가져와야 해서, 
기존 `경로 db`에 `area`를 추가해야 할 것 같습니다.

2. 따라서 경로 생성 API도 마찬가지로, `area`인자를 추가해야 할 것 같습니다.

3. 또한 위 페이지에서 n개의 루트에 대한 카드만을 생성해 주려고 하는데,  
루트의 추천수 혹은 담은수를 기준으로 표시하려고 합니다.
따라서 `경로` db에 `추천수` 혹은 `담은수`도 추가하면 어떨까요?

**Comment by labyu** [comment]
[1. 2.] `area`에 대한 정보는 DB에 추가하고 API도 구현하겠습니다. 혹시 Area 코드에 대한 정보는 어디에서 얻을 수 있는지 링크 첨부해주시면 감사합니다.

[3.] 추천수는 좋아요와 같은 개념인지 궁금합니다. 담은수의 경우에는 릴레이션을 통해 현재 스키마로도 구할 수 있습니다.

**Comment by tech-hoon** [comment]
1. 여기서 확인하실 수 있습니다. 확정은 아니며, 바뀔 수 있습니다.
https://github.com/TravelPlan-Project/TravelPlan/tree/develop/frontend/src/assets

2. 아 네 맞습니다. 좋아요(추천)수로 정렬하면 좋을 것 같아요 !

**Comment by labyu** [comment]
지역코드 확인했습니다. 그런데 어떤 장소가 해당 지역코드에 포함되는지 어떤 조건으로 확인해야할까요?
