### ISSUE TITLE
[backend] adoc 파일 리팩토링

### ISSUE THREAD

**Issue by donup088** [TravelPlan-Project/TravelPlan#76]
요청 HTTP
include::{snippets}/route-update/http-request.adoc[]
include::{snippets}/route-update/path-parameters.adoc[]
include::{snippets}/route-update/request-fields.adoc[]

성공 응답 HTTP
include::{snippets}/route-update/http-response.adoc[]

위의 코드를 아래코드처럼 바꾸면 어떨까요??

operation::route-update[snippets='request-fields,path-parameters,http-request,http-response']

**Comment by labyu** [comment]
> 요청 HTTP
> include::{snippets}/route-update/http-request.adoc[]
> include::{snippets}/route-update/path-parameters.adoc[]
> include::{snippets}/route-update/request-fields.adoc[]
> 
> 성공 응답 HTTP
> include::{snippets}/route-update/http-response.adoc[]
> 
> 위의 코드를 아래코드처럼 바꾸면 어떨까요??
> 
> operation::route-update[snippets='request-fields,path-parameters,http-request,http-response']

결과 동일하고 작성할때 자동완성 힌트 잘 나오면 좋은 것 같습니다

**Comment by donup088** [comment]
route-update 까지는 자동완성힌트가 나오지만 snippets 은 자동완성힌트는 안나오고 해당 snippet이 없으면 인텔리제이에서 경고로 노란줄을 만들어주네요

**Comment by donup3** [comment]
route-update까지는 자동완성 힌트가 나오지만 snippet은 자동완성 힌트는 안나오고 해당 snippet이 없으면 인텔리제이에서 경고로 노란줄을 만들어주네요

**Comment by labyu** [comment]
> route-update 까지는 자동완성힌트가 나오지만 snippets 은 자동완성힌트는 안나오고 해당 snippet이 없으면 인텔리제이에서 경고로 노란줄을 만들어주네요

[snippets='request-fields,path-parameters,http-request,http-response'] 이부분 작성할때 자동완성이 안나오면 'request-fields'를 직접 타이핑 해야하는건가요?

**Comment by donup088** [comment]
네네 api가 많아지면 adoc 파일에 코드가 많아져서 코드를 줄일려다보니까 사용했었는데 그래서 전에는 복사해서 사용했어요

**Comment by labyu** [comment]
이 이슈는 다음에 문제가 되면 다시 열겠습니다
